[package]
name = "sql_insight"
version = "0.1.0"
edition = "2021"
authors = ["Takahiro Ebato <takahiro.ebato@gmail.com>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.6" }
