name: Main

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v3
      - name: Up docker
        run: docker compose up -d ruby-rust
      - name: bundle install
        run: docker compose exec ruby-rust /bin/bash -c 'bundle install'
      - name: Check rubocop
        run: docker compose exec ruby-rust /bin/bash -c 'bundle exec rake rubocop'
      - name: Check syntax tree
        run: docker compose exec ruby-rust /bin/bash -c 'bundle exec rake stree:check'
      - name: Check Rust
        run: docker compose exec ruby-rust /bin/bash -c 'cargo clippy'
  test-ruby:
    runs-on: ubuntu-latest
    name: Ruby-${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.0.2'
          - '3.1.4'
          - '3.2.2'
          - '3.3.0'
    steps:
      - uses: actions/checkout@v3
      - name: Up docker
        run: RUBY_VERSION=${{ matrix.ruby }} docker compose up -d ruby-rust
      - name: Run Tests
        run: docker compose exec ruby-rust /bin/bash -c 'bundle install && bundle exec rake compile && bundle exec rake spec'
